#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

cd src
./Allwmake
if [ $? -ne 0 ]
then
 echo "library did not compile"
 exit 1
fi
cd ..


#------------------------------------------------------------------------------
