#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

cd offline
wmake
if [ $? -ne 0 ]
then
 echo "library did not compile"
 exit 1
fi
cd ..

cd online
if [ $? -ne 0 ]
then
 echo "library did not compile"
 exit 1
fi
wmake
cd ..


#------------------------------------------------------------------------------
